derek_love/rails/DojoSecrets/config/routes.rb
Rails.application.routes.draw do
  post 'likes/create'

  delete 'likes/destroy'

  root :to => "users#new"

  resources :users

  resources :sessions

  resources :secrets

end

derek_love/rails/DojoSecrets/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :secret
end

derek_love/rails/DojoSecrets/app/models/secret.rb
class Secret < ActiveRecord::Base
  belongs_to :user, required: true

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  
  validates :content, presence: true, length: { minimum: 2 }
end

derek_love/rails/DojoSecrets/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :secrets
  has_many :likes, dependent: :destroy
  has_many :secrets_liked, through: :likes, source: :secret


  validates :first_name, presence: true
  validates :last_name, presence: true
  
  EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
  validates :email, presence: true, uniqueness: { case_sensitive: false}, format: { with: EMAIL_REGEX }

  before_create :downcase

  private
    def downcase
      self.first_name.downcase!
      self.last_name.downcase!
      self.email.downcase!
    end
end

derek_love/rails/DojoSecrets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session.key? "user_id"
  end
  
  def require_login
    redirect_to new_session_path if session[:user_id] == nil
  end
end

derek_love/rails/DojoSecrets/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create( new_like )
    redirect_to secrets_path
  end

  def destroy
    @like = Like.find_by(user_id: current_user)
    if current_user == @like.user_id
      @like.destroy
      redirect_to secrets_path
    end
  end

  private
    def new_like
      params.require(:like).permit(:user_id, :secret_id)
    end
end

derek_love/rails/DojoSecrets/app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

    def index
        @secrets = Secret.eager_load(:user).all
    end

    def create
        @secret = Secret.create( new_secret )
        if @secret.valid?
            redirect_to user_path(current_user)
        else
            flash[:errors] = @secret.errors.full_messages
            redirect_to user_path(current_user)
        end
    end

    def destroy
        @secret = Secret.find_by(id: params[:id])
        if current_user == @secret.user
            @secret.destroy
            redirect_to user_path(current_user)
        else
            redirect_to secrets_path
        end
    end

    private
        def new_secret
            params.require(:secret).permit(:content, :user_id)
        end
end

derek_love/rails/DojoSecrets/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_login, except: [:destroy]

    def new
        # render login page
    end

    # log in user
    def create
        @user = User.find_by(email: params[:email])
        if @user
            if @user.authenticate(params[:password])
                session[:user_id] = @user.id
                redirect_to "/users/#{session[:user_id]}"
            else
                flash[:errors] = "Invalid email/password combination"
                redirect_to new_session_path
            end
        else
            flash[:errors] = "Invalid email/password combination"
            redirect_to new_session_path
        end
    end

    # log out user
    def destroy
        session.delete :user_id

        redirect_to new_session_path
    end
end

derek_love/rails/DojoSecrets/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :this_user, except: [:new, :create]

  def new
  end

  def create
    @user = User.create( new_user )
    if @user.valid?
      session[:user_id] = @user.id

      redirect_to new_session_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
  end

  def edit
  end
  
  def update
    @user = User.find(current_user)
    @user.update( new_user )
    if @user.valid?
      redirect_to "/users/#{@user.id}"
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to "/users/#{@user.id}/edit"
    end
  end

  def destroy
    @user = User.find(current_user)
    @user.destroy

    redirect_to new_user_path
  end

  private
    def new_user
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def this_user
      if params[:id].to_i != current_user.id
        redirect_to user_path(current_user.id)
      end
    end
end

derek_love/rails/DojoSecrets/app/helpers/likes_helper.rb
module LikesHelper
end

derek_love/rails/DojoSecrets/app/helpers/secrets_helper.rb
module SecretsHelper
end

derek_love/rails/DojoSecrets/app/helpers/users_helper.rb
module UsersHelper
end

derek_love/rails/DojoSecrets/app/views/users/edit.html.erb
<h1>Edit <%= @user.first_name %></h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p id="errors">
            <%= error %>
        </p>
    <% end %>
<% end %>

<form action="/users/<%= @user.id %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <input type="hidden" name="_method" value="patch">

    <label for="user[first_name]">First Name</label>
    <input type="text" name="user[first_name]" value="<%= @user.first_name %>">

    <label for="user[last_name]">Last Name</label>
    <input type="text" name="user[last_name]" value="<%= @user.last_name %>">

    <label for="user[email]">Email</label>
    <input type="email" name="user[email]" value="<%= @user.email %>">

    <input type="submit" value="Update">
</form>

<a href="/users/<%= @user.id %>" data-method="delete">Delete Account</a>

derek_love/rails/DojoSecrets/app/views/users/new.html.erb
<h1>Register Here!</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p id="errors">
            <%= error %>
        </p>
    <% end %>
<% end %>

<form action="/users" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label for="user[first_name]">First Name</label>
    <input type="text" name="user[first_name]">

    <label for="user[last_name]">Last Name</label>
    <input type="text" name="user[last_name]">

    <label for="user[email]">Email</label>
    <input type="email" name="user[email]">

    <label for="user[password]">Password</label>
    <input type="password" name="user[password]">

    <label for="user[password_confirmation]">Password Confirmation</label>
    <input type="password" name="user[password_confirmation]">

    <input type="submit" value="Register">
</form>

derek_love/rails/DojoSecrets/app/views/users/show.html.erb
<h1><%= current_user.first_name %></h1>

<% if flash[:errors] %>
    <p id="errors">
        <%= flash[:errors] %>
    </p>
<% end %>

<form action="<%= secrets_path %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <textarea name="secret[content]" cols="30" rows="10"></textarea>
    <input type="hidden" name="secret[user_id]" value="<%= current_user.id %>">
    <input type="submit" value="Create Secret">
</form>

<div id="user_secrets">
    <h4>My Secrets</h4>
    <% current_user.secrets.each do |secret| %>
        <p><%= secret.content %></p>
        <a href="<%= secret_path(secret.id) %>" data-method="delete">
            <button>Delete Secret</button>
        </a>
    <% end %>
</div>